version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - NODE_ENV=production
      - PGUSER=${POSTGRES_USER:-postgres}
      - PGHOST=${POSTGRES_HOST:-db}
      - PGDATABASE=${POSTGRES_DB:-map1}
      - PGPASSWORD=${POSTGRES_PASSWORD:-7632}
      - PGPORT=${POSTGRES_PORT:-5432}
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-7632}
      - POSTGRES_DB=${POSTGRES_DB:-map1}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 